//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComidaChinaRest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePedido
    {
        public int id_detalle { get; set; }
        public Nullable<int> id_pedido { get; set; }
        public Nullable<int> id_producto { get; set; }
        public int cantidad { get; set; }
        public decimal precio_unitario { get; set; }
        public decimal total_producto { get; set; }
    
        public virtual Pedido Pedido { get; set; }
        public virtual Productos Productos { get; set; }
    }
}
